version: '3.9'
services:
  adminer:
    container_name: telegrammer_adminer
    image: adminer:4.8.1
    ports:
      - 8080:8080
    env_file: .env
    volumes:
      - .:/application:cached

  redisui:
    container_name: telegrammer_redisui
    image: rediscommander/redis-commander:latest
    ports:
      - 8081:8081
    env_file: .env