version: '3.9'
services:
  console:
    container_name: telegrammer_console
    command: 'bin/console'
    build: .
    working_dir: /application
    stdin_open: true
    tty: true
    env_file: .env.test
    volumes:
      - .:/application:cached
      - bundle-cache:/usr/local/bundle:cached
    depends_on:
      - database
      - redis
    networks:
      - default
      - web

  database:
    container_name: telegrammer_database
    image: postgres:10.3-alpine
    command: postgres -c 'max_connections=150'
    ports:
      - 5433:5432
    env_file: .env.test
    volumes:
      - .:/application:cached
      - db-data:/var/lib/postgresql/data:cached

  redis:
    container_name: telegrammer_redis
    image: redis:4.0-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    env_file: .env.test
    ports:
      - 6380:6379
    volumes:
      - redis-storage:/data:cached
      - ./docker-configs/redis/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  db-data: null
  bundle-cache: null
  redis-storage: null

networks:
  web: