# Set desired concurrency here. By default 1
:concurrency: 1
:logfile: log/sidekiq.log

:queues:
  - critical
  - default
  - low

# :schedule:
  # WorkerClass:
  #   cron: '0 0 1 * *' # Runs every month
  #   class: WorkerClass
  #   description: 'Worker description'
